package com.example.langgraph4jdemo.langchain;

import org.bsc.langgraph4j.action.NodeAction;
import org.springframework.stereotype.Component;

import java.util.Map;

@Component
public class DraftWithLangChainNode implements NodeAction<LangChainState> {

    private final WritingAssistant writingAssistant;

    public DraftWithLangChainNode(WritingAssistant writingAssistant) {
        this.writingAssistant = writingAssistant;
    }

    @Override
    public Map<String, Object> apply(LangChainState state) {
        System.out.println("DraftWithLangChainNode executing. Topic: " + state.topic());
        String draft = writingAssistant.createDraft(state.topic());
        System.out.println("LangChain4j draft: " + draft);
        return Map.of(
                LangChainState.DRAFT_KEY, draft,
                LangChainState.MESSAGES_KEY, "draft generated by LangChain4j"
        );
    }
}
